### ISSUE TITLE
No module named ply_from_array

### ISSUE THREAD

**Issue by kaygudo** [mmolero/pypoisson#1]
Hello,

I recently installed pypoisson.When i try to run the example code it gives following error
 "No module named ply_from_array" while importing "from ply_from_array import points_normals_from"
any clue or suggestions?

Thank you

**Comment by mmolero** [comment]
@kaygudo you need in the same folder you are running your script the following file: 
https://github.com/mmolero/pypoisson/blob/master/example/ply_from_array.py

**ply_from_array** does not form part of **pypoisson**, it is  a data reader only.

**Comment by AcrimoniousMirth** [comment]
@mmolero Okay, so put it in the same folder, now I'm getting
    `ImportError: cannot import name 'point_normals_from'`

**EDIT** This turns out to be a mismatch between the library and the horse example (which I'm trying to follow) whereby the example uses `point` singular and the library `points` plural.
Also, getting this error:
    `Traceback (most recent call last):
      File "poissonTest.py", line 10, in <module>
        faces, vertices = poisson_reconstruction(points, normals, depth=10)
      File "src/pypoisson.pyx", line 100, in pypoisson.poisson_reconstruction
      File "src/pypoisson.pyx", line 112, in pypoisson._poisson_reconstruction
      File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
    TypeError: expected bytes, str found`

**Comment by AcrimoniousMirth** [comment]
Also I found I needed to separately install cython and then `sudo python3` to build and install the setup.py. May need to update your **readme**, also mentioning `cd`'ing into your directory. 
Also, I'm unfamiliar with binders, how do I actually get this to work with the **poissonrecon** library? Thanks :)

**Comment by mmolero** [comment]
Update readme.md thanks
