### ISSUE TITLE
Bug in the poisson_reconstruction function?

### ISSUE THREAD

**Issue by danielnflam** [mmolero/pypoisson#4]
Built fine, installed fine, but I got a problem from here and I was wondering if you know what to do:

Traceback (most recent call last):
  File "main.py", line 44, in <module>
    faces, vertices = poisson_reconstruction(points, normals, depth=10)
  File "src/pypoisson.pyx", line 100, in pypoisson.poisson_reconstruction (src/pypoisson.cpp:2413)
  File "src/pypoisson.pyx", line 112, in pypoisson._poisson_reconstruction (src/pypoisson.cpp:2568)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (src/pypoisson.cpp:6006)
TypeError: expected bytes, str found

**Comment by mmolero** [comment]
I suppose that you ran the example successfully right?

How is your python environment?  Python version cython version?

**Comment by clemaitre58** [comment]
I have exactly the same error on the example :  
---> 10 faces, vertices = poisson_reconstruction(points, normals, depth=10)
     11 
     12 #Helper function to save mesh to PLY Format

src/pypoisson.pyx in pypoisson.poisson_reconstruction (src/pypoisson.cpp:2671)()

src/pypoisson.pyx in pypoisson._poisson_reconstruction (src/pypoisson.cpp:2830)()

~/miniconda3/lib/python3.6/site-packages/pypoisson.cpython-36m-x86_64-linux-gnu.so in string.from_py.__pyx_convert_string_from_py_std__in_string (src/pypoisson.cpp:6736)()

TypeError: expected bytes, str found
--------------

Config : 

Python 3.6.1 :: Continuum Analytics, Inc.
cython                    0.25.2                   py36_0

**Comment by ghost** [comment]
It's run perfect over Python2.7, 
fails compiling with  python >3
